name: Deploy to AP Server

on:
  workflow_run:
    workflows: [ "Build and Upload to Nexus" ]  # build.yml의 name: 필드와 정확히 일치해야 함
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AP_SERVER_HOST }}
          username: ${{ secrets.AP_SERVER_USER }}
          key: ${{ secrets.AP_SERVER_SSH_KEY }}
          port: 22
          script: |
            export NEXUS_URL=${{ secrets.NEXUS_URL }}
            export JAR_NAME="ghbaek-app-0.0.1-SNAPSHOT.jar"
            export NEXUS_USER="${{ secrets.NEXUS_USERNAME }}"
            export NEXUS_PASSWORD="${{ secrets.NEXUS_PASSWORD }}"
            bash /app/gh.project/deploy.sh

